### ISSUE TITLE
Variable binding in a condition requires an initializer

### ISSUE THREAD

**Issue by my931117** [ritmillio/expo-router-starter-kit#33] opened 2023-11-09 03:29 UTC
I got an error when I used your tool to package ios.
Variable binding in a condition requires an initializer

**Comment by my931117** [comment] 2023-11-09 03:30
> I got an error when I used your tool to package ios. Variable binding in a condition requires an initializer

Please help me

**Comment by my931117** [comment] 2023-11-09 03:32
![image](https://github.com/ritmillio/expo-router-starter-kit/assets/30072361/2315d116-58b3-46a4-a31c-7da4c2601406)

**Comment by my931117** [comment] 2023-11-09 03:32
![image](https://github.com/ritmillio/expo-router-starter-kit/assets/30072361/bd9f7193-66e3-4ef2-9a34-82470bb5ba42)

**Comment by kewinzaq1** [comment] 2023-11-12 16:38
@my931117 Hi, could you provide steps to reproduce?

**Comment by ritmillio** [comment] 2023-11-27 21:08
Since we weren't be able to reproduce the bug and no-one else reported similar behaviour i close this issue for now.

**Closed by ritmillio** 2023-11-27 21:08 UTC
